version: '3.8'

services:
  mysql:
    container_name: goraebab_mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      goraebab_network:
        ipv4_address: 172.18.0.20
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5


  backend:
    container_name: goraebab_spring
    image: spring:latest
    build:
      context: ./
    ports:
      - "2387:2387"
      - "5005:5005"
    environment:
      spring.profiles.active: mysql
      spring.datasource.url: jdbc:mysql://172.18.0.20:3306/goraebab
      spring.datasource.username: root
      spring.datasource.password: root
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      goraebab_network:
        ipv4_address: 172.18.0.10
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  goraebab_network:
    name: goraebab_network
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16